apiVersion: v1
kind: Service
metadata:
  name: backend-service-app-1
spec:
  selector:
    app: nest-play-app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # this targetPort should the port of the app running in the container inside the pod
  type: NodePort
