apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-play-app-2
  labels:
    app: nest-play-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-play-app-2
  template:
    metadata:
      name: nest-play
      labels:
        app: nest-play-app-2

    spec:
      containers:
        - name: nest-backend
          # image: docker.io/ibakshay/nest-play:2.0.0
          image: gcr.io/google-samples/hello-app:1.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "1"
 #             ephemeral-storage: 1Gi                                                                                                                                                                                    │
              memory: 512Mi
            limits:
              cpu: "1"
#              ephemeral-storage: 1Gi                                                                                                                                                                                    │
              memory: 512Mi
      restartPolicy: Always

