apiVersion: v1
kind: Service
metadata:
  name: backend-service-app-2
spec:
  selector:
    app: nest-play-app-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # this targetPort should the port of the app running in the container inside the pod
  type: NodePort
